import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div style={{
          minHeight: '100vh',
          display: 'flex',
          flexDirection: 'column',
        }}>
          <main style={{ flex: 1 }}>
            {children}
          </main>
          <footer
            style={{
              padding: '24px 0',
              borderTop: '1px solid var(--foreground)',
              textAlign: 'center',
              fontSize: 16,
              color: 'var(--foreground)',
              background: 'var(--background)',
            }}
          >
            <nav>
              <a
                href="/terms-of-service"
                style={{
                  margin: '0 16px',
                  color: 'var(--foreground)',
                  textDecoration: 'underline',
                  opacity: 0.85,
                }}
              >
                Terms of Service
              </a>
              <span style={{ color: 'var(--foreground)', opacity: 0.5 }}>|</span>
              <a
                href="/privacy-policy"
                style={{
                  margin: '0 16px',
                  color: 'var(--foreground)',
                  textDecoration: 'underline',
                  opacity: 0.85,
                }}
              >
                Privacy Policy
              </a>
              <span style={{ color: 'var(--foreground)', opacity: 0.5 }}>|</span>
              <a
                href="/contact-us"
                style={{
                  margin: '0 16px',
                  color: 'var(--foreground)',
                  textDecoration: 'underline',
                  opacity: 0.85,
                }}
              >
                Contact Us
              </a>
              <span style={{ color: 'var(--foreground)', opacity: 0.5 }}>|</span>
              <a
                href="/careers"
                style={{
                  margin: '0 16px',
                  color: 'var(--foreground)',
                  textDecoration: 'underline',
                  opacity: 0.85,
                }}
              >
                Careers
              </a>
            </nav>
            <div style={{ marginTop: 8, fontSize: 14, opacity: 0.7 }}>
              &copy; {new Date().getFullYear()} parodypipeline.com. All rights reserved.
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
