import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from '../context/UserContext';
import Header from '../components/Header';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "parodypipeline.com",
  description: "Generated by create next app",
  icons: {
    icon: '/assets/images/Parody_favico.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <UserProvider>
          <div className="flex flex-col min-h-screen">
            <Header />
            <main className="flex-1">
              {children}
            </main>
            <footer
              style={{
                padding: '24px 0',
                borderTop: '1px solid var(--foreground)',
                textAlign: 'center',
                fontSize: 16,
                color: 'var(--foreground)',
                background: 'var(--background)',
              }}
            >
              <nav>
                <a
                  href="/terms-of-service"
                  style={{
                    margin: '0 16px',
                    color: 'var(--foreground)',
                    textDecoration: 'underline',
                    opacity: 0.85,
                  }}
                >
                  Terms of Service
                </a>
                <span style={{ color: 'var(--foreground)', opacity: 0.5 }}>|</span>
                <a
                  href="/privacy-policy"
                  style={{
                    margin: '0 16px',
                    color: 'var(--foreground)',
                    textDecoration: 'underline',
                    opacity: 0.85,
                  }}
                >
                  Privacy Policy
                </a>
                <span style={{ color: 'var(--foreground)', opacity: 0.5 }}>|</span>
                <a
                  href="/contact-us"
                  style={{
                    margin: '0 16px',
                    color: 'var(--foreground)',
                    textDecoration: 'underline',
                    opacity: 0.85,
                  }}
                >
                  Contact Us
                </a>
                <span style={{ color: 'var(--foreground)', opacity: 0.5 }}>|</span>
                <a
                  href="/careers"
                  style={{
                    margin: '0 16px',
                    color: 'var(--foreground)',
                    textDecoration: 'underline',
                    opacity: 0.85,
                  }}
                >
                  Careers
                </a>
              </nav>
              <div style={{ marginTop: 8, fontSize: 14, opacity: 0.7 }}>
                &copy; {new Date().getFullYear()} parodypipeline.com. All rights reserved.
              </div>
            </footer>
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
